package com.test.verifier.domains.business.vo;

/**
 * Created by mandar on 22-01-2017.
 */
public enum TransactionReasonCode {
    LOSS_PROVISION_REGISTERED,
    LOSS_INCURRED_BY_PRODUCT,
    OPERATING_EXPENSE_PROVISION_REGISTERED,
    OPERATING_EXPENSE_PROVISION_EXHAUSETED,
    OPERATING_EXPENSE_PROVISION_CORRECTED,
    NODAL_PROVISION_REGISTERED,
    BENEFITS_PROVISION_REGISTERED,
    BENEFITS_PROVISION_EXHAUSTED,
    BENEFITS_PROVISION_CORRECTED,
    TAXES_PROVISION_REGISTERED,
    TAXES_PROVISION_EXHAUSTED,
    TAXES_PROVISION_CORRECTED,
    TAXES_DEDUCTED,
    OTHERS_PROVISION_REGISTERED,
    OTHERS_PROVISION_EXHAUSTED,
    OTHERS_PROVISION_CORRECTED,
    PURCHASE_COST_PROVISION_REGISTERED,
    PURCHASE_COST_PROVISION_EXHAUSTED,
    PURCHASE_COST_PROVISION_CORRECTED,
    PURCHASE_COST_PROVISION_DEBITED,
    REVENUE_ADDED_BY_PRODUCT,
    PROFIT_ADDED_BY_PRODUCT,
    EXCESS_PROFIT_ADDED_BY_PRODUCT,
    LOAN_REQUESTED_BY_PRODUCT,
    ADVANCE_PAYMENT_RECEIVED,
    ADVANCE_PAYMENT_ADJUSTED
}
