package com.verifier.domains.business.vo;

/**
 * Created by mandar on 19-02-2017.
 */
public enum CommonOperatingExpenseHeader {
    EXP_SOFTWARE_MAINTENANCE_ENHANCEMENT,
    EXP_COMMUNICATION_CHARGES,
    EXP_ELECTRICITY,
    EXP_RENTAL_PREMISE_MAINTENENANCE,
    EXP_PERSONNEL,
    EXP_TAXES_SERVICE_CHARGES,
    EXP_HOUSEKEEPING,
    EXP_BUSINESS_TRAVEL_ACCOMODATION,
    EXP_STATIONARY_OFFICE_MATERIAL,
    EXP_RENEWALS_LICENCE_CERTIFICATES,
    EXP_LOGISTICS,
    EXP_EMPLOYEE_WELFARE_FACILITIES,
    EXP_RECRUITMENT,
    EXP_SALES,
    EXP_LOAN_REPAYMENTS
}
