package com.verifier.domains.business.vo;

/**
 * Created by mandar on 11/21/2017.
 */
public enum ProvisionChangeReason {
    LESS_PURCHASE_COST_PROVISION,
    EXCESS_PURCHASE_COST_PROVISION,
    LESS_SUBSCRIPTIONSPECIFICEXPENSE_PROVISION,
    EXCESS_SUBSCRIPTIONSPECIFICEXPENSE_PROVISION,
    LESS_TAXES_PROVISION,
    EXCESS_TAXES_PROVISION,
    LESS_BENEFITS_PROVISION,
    EXCESS_BENEFITS_PROVISION
}
