package com.verifier.domains.business.vo;

/**
 * Created by mandar on 18-02-2017.
 */
public enum RecommendationReason {
    SUBSCRIPTION_COUNT_INCREASED, SUBSCRIPTION_COUNT_DECREASED,PURCHASE_PRICE_INCREASED,RECOVER_FROM_LOSS,DELIVERY_COUNT_PER_PERIOD_INCREASED,DELIVERY_COUNT_PER_PERIOD_DECREASED
}
