package com.affaince.subscription.pojos;

public enum EligibilityParameter {
    TOTALSUBSCRIPTIONAMOUNT,
    CURRENTSUBSCRIPTIONAMOUNT,
    TOTALSUBSCRIPTIONPROFIT,
    TOTALLOYALTYPERIOD,
    CURRENTSUBSCRIPTIONPERIOD;
}
