package com.affaince.accounting.journal.qualifiers;

public enum NatureOfTransaction {
    CAPITAL_INVESTMENT,
    GOODS_PURCHASE_BY_BUSINESS,
    GOODS_DELIVERY_TO_SUBSCRIBER,
    PAYMENT_RECEIVED_FROM_SUBSCRIBER,
    PAYMENT_MADE_TO_SUPPLIER,
    PAYMENT_MADE_TO_SERVICE_PROVIDER,
    TAX_PAYMENT,
    REWARDS_OFFERED_TO_SUBSCRIBER,
    REWARDS_REDEEMED_BY_SUBSCRIBER,
    PAYMENT_OF_RENT,
    STATIONARY_OR_FURNITURE_PURCHASE
}
