package com.affaince.subscription.business.vo;

/**
 * Created by mandar on 22-01-2017.
 */
public enum TransactionReasonCode {
    LOSS_INCURRED_BY_PRODUCT,
    OPERATING_EXPENSE_PROVISION_EXHAUSETED,
    OPERATING_EXPENSE_PROVISION_CORRECTED,
    BENEFITS_PROVISION_EXHAUSTED,
    BENEFITS_PROVISION_CORRECTED,
    TAXES_PROVISION_EXHAUSTED,
    TAXES_PROVISION_CORRECTED,
    REVENUE_ADDED_BY_PRODUCT,
    PROFIT_ADDED_BY_PRODUCT,
    EXCESS_PROFIT_ADDED_BY_PRODUCT,
    LOAN_REQUESTED_BY_PRODUCT,
    ADVANCE_PAYMENT_RECEIVED
}
