package com.affaince.accounting.client;

public enum PartyTypes {
    SUPPLIER_OF_GOODS,
    SERVICE_PROVIDER,
    SUBSCRIBER,
    DISTRIBUTION_SUPPLIER,
    MERCHANT,
    TAX_AUTHORITY,
    OWNER_OF_PREMISE_RENTED,

    SUBSCRIBER_REWARDS,
    BUSINESS_CAPITAL,
    BUSINESS_GOODS,
    BUSINESS_BANK_ACCOUNT,
    EMPLOYEE,
    FIXED_ASSETS,
    BUSINESS;
}
